apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myjavapost
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: javapost
  source:
    path: "HelmCharts/MyChart1"
    repoURL: "git@github.com:raiym2048/homechief.git"
    targetRevision: HEAD
    helm:
      valueFiles:
        - values_dev.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
