apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }} # Сервис будет искать по этим меткам
    spec:
      containers:
        - name: {{ .Release.Name }}-web
          image: {{ .Values.container.image }}
          ports:
            - containerPort: 8090
        - name: {{ .Release.Name }}-bd
          image: {{ .Values.container.postgres_image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres_image.env[0].value }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres_image.env[1].value }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres_image.env[2].value }}
            - name: POSTGRES_HOST_AUTH_METHOD
              value: {{ .Values.postgres_image.env[3].value }}
ы