apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name: {{ .Release.Name }}-web
          image: {{ .Values.container.image }}
          ports:
            - containerPort: 8090

        - name: {{ .Release.Name }}-bd
          image: {{ .Values.container.postgres_image }}
          
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
