apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }} # Выбираем POD-ы с этими метками
  ports:
    - name: {{ .Release.Name }}-listener
      protocol: TCP
      port: 80
      targetPort: 8090
    - name: {{ .Release.Name }}-postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
